// swift-tools-version:6.0
// Generated by OID4VCgo's mobile/ios/package-swift-release.sh: edit it
// there. Mobile.xcframework is OID4VCgo's Go wallet (the Go "mobile"
// package), built with gomobile; OID4VCWallet is its Swift API.
import PackageDescription

let package = Package(
    name: "OID4VCWallet",
    platforms: [.iOS(.v16), .macOS(.v13)],
    products: [.library(name: "OID4VCWallet", targets: ["OID4VCWallet"])],
    targets: [
        .binaryTarget(name: "Mobile", url: "https://github.com/IDFoundry/OID4VCgo-wallet-swift/releases/download/0.6.3/Mobile.xcframework.zip", checksum: "0c9996877756d6259e34678a41e36b649b3586e41560b77e588fa40c11f36a3c"),
        .target(name: "OID4VCWallet", dependencies: ["Mobile"]),
    ]
)
