// swift-tools-version:6.0
// Generated by OID4VCgo's mobile/ios/package-swift-release.sh: edit it
// there. Mobile.xcframework is OID4VCgo's Go wallet (the Go "mobile"
// package), built with gomobile; OID4VCWallet is its Swift API.
import PackageDescription

let package = Package(
    name: "OID4VCWallet",
    platforms: [.iOS(.v16), .macOS(.v13)],
    products: [.library(name: "OID4VCWallet", targets: ["OID4VCWallet"])],
    targets: [
        .binaryTarget(name: "Mobile", url: "https://github.com/IDFoundry/OID4VCgo-wallet-swift/releases/download/0.8.2/Mobile.xcframework.zip", checksum: "be7b80d1873fb09ea9ad7d23ba1f9cfa73661dbb525c24818cbb8a75f9a038fe"),
        .target(name: "OID4VCWallet", dependencies: ["Mobile"]),
    ]
)
